apiVersion: v1
kind: ServiceAccount
metadata:
  name: opencsd-metric-collector
  namespace: default
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: opencsd-metric-collector
  namespace: default
subjects:
- kind: ServiceAccount
  name: opencsd-metric-collector
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
