apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metric-power-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: metric-power
  selector:
    matchLabels:
      app: metric-power
