apiVersion: apps/v1
kind: Deployment
metadata:
  name: opencsd-metric-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      name: opencsd-metric-collector
  template:
    metadata:
      labels:
        name: opencsd-metric-collector
    spec:
      serviceAccountName: opencsd-metric-collector
      imagePullSecrets:
        - name: regcred
      containers:
        - name: opencsd-metric-collector
          image: ketidevit2/opencsd-metric-collector:v0.0.1
          command:
          - opencsd-metric-collector
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: INFLUX_IP
              value: "10.0.4.87"
            - name: INFLUX_PORT
              value: "30703"
            - name: INFLUX_USERNAME
              value: "keti"
            - name: INFLUX_PASSWORD
              value: "ketilinux"
            - name: OPERATOR_NAME
              value: "opencsd-metric-collector"
          volumeMounts:
            - mountPath: /mnt
              name: metric-power
        - name: instance-metric-collector
          image: ketidevit2/instance-metric-collector:v0.0.1
          imagePullPolicy: Always
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: DEBUGG_LEVEL
            value: "LEVEL1"
          - name: NODE_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: INFLUX_IP
            value: "10.0.4.87"
          - name: INFLUX_PORT
            value: "30701"
          - name: INFLUX_USERNAME
            value: "keti"
          - name: INFLUX_PASSWORD
            value: "ketilinux"
            #volumeMounts:
            #- mountPath: /mnt
            #  name: metric-power
      volumes:
       - name: metric-power
         hostPath:
           type: Directory
           path: /sys/devices/virtual/powercap/intel-rapl
      tolerations:
        - key: node.kubernetes.io/not-ready
          effect: NoExecute
          tolerationSeconds: 0
        - key: node.kubernetes.io/unreachable
          effect: NoExecute
          tolerationSeconds: 0
