apiVersion: v1
kind: PersistentVolume
metadata:
  name: metric-power
  labels:
    app: metric-power
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  storageClassName: metric-power
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/sys/class/powercap"
