apiVersion: v1
kind: Service
metadata:
  name: opencsd-metric-collector
  namespace: management-platform
  labels:
    name: opencsd-metric-collector
    namespace: management-platform
spec:
  type: NodePort
  ports:
    - port: 40801
      targetPort: 40801
      nodePort: 30003
      protocol: TCP
  selector:
    name: opencsd-metric-collector
    namespace: management-platform
